name: "test"
on: push

env:
  GODOT_VERSION: 3.4

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: GUT tests
        run: |
          godot -d -s --path . addons/gut/gut_cmdln.gd -gdir=res://test -ginclude_subdirs -gexit
